global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "go_app"
    static_configs:
      - targets: ["app:9091"] # Replace with your Go app metrics endpoint